# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38c5d344d2558c1fe2828708bca5818c0bb6fd7bee59fa2ba032408234924ebda34972c735c40ca3942859aea047f92588d063eef05d9c9a4540004036787769

test:
  secret_key_base: 0be95a25571d828b0304eaa3cd316a504cbd6be7e34bc6b5bdc7637f153613be5b05f0dabe9a6499b1ff3e140895a3fa0b39803a66d7945b6d7dec326ad35dcd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
